import { create } from '@storybook/theming/create';

export default create({
  base: 'dark',
  brandTitle: 'Tapsi Web Components',
  brandUrl: 'https://tap30.github.io/web-components',
  brandTarget: '_blank',
  colorPrimary: '#a8b1ff',
  colorSecondary: '#a8b1ff',
  appBg: '#161618',
  appContentBg: '#1b1b1f',
  appPreviewBg: '#1b1b1f',
  appBorderColor: '#2e2e32',
  appBorderRadius: 8,
  textColor: 'rgba(235, 235, 245, 0.6)',
  textInverseColor: '#ffffff',
  barTextColor: '#9E9E9E',
  barSelectedColor: '#a8b1ff',
  barHoverColor: '#a8b1ff',
  barBg: '#161618',
  inputBg: '#1b1b1f',
  inputBorder: '#2e2e32',
  inputTextColor: '#ffffff',
  inputBorderRadius: 8,
  booleanBg: '#161618',
  textMutedColor: 'rgba(235, 235, 245, 0.6)',
});
