/**
 * Integrity check for the committed token sets.
 *
 * The sets under `src/` are generated by applying the rules in AGENTS.md to the
 * exports in `figma-output-jsons/`, but nothing enforces that at build time — so
 * this script re-derives every expected name and value straight from the
 * exports and compares them against what is committed.
 *
 * That matters because the failure modes here are invisible on inspection. A
 * token referencing a variable nobody defines is valid CSS and simply renders
 * nothing. A TS set that has drifted from its stylesheet looks fine in both
 * files. A token dropped during a re-export leaves no trace at all.
 *
 * For every export, it asserts:
 *
 *   1. coverage — every exported token exists in both the CSS and the TS set,
 *      and neither contains anything the export does not
 *   2. naming — the CSS name is the kebab-cased Figma path prefixed `--tapsi-`,
 *      and the TS path is its camelCase equivalent
 *   3. values — literals match the documented transforms (px→rem, alpha→rgba,
 *      weight name→number, family fallback)
 *   4. layering — a theme token references a primitive rather than inlining a
 *      literal, the only sanctioned exception being Typography/Line-Height,
 *      which the Figma export itself gives as raw numbers
 *   5. agreement — the TS value equals what the CSS `var()` chain resolves to
 *
 * Run with `pnpm --filter @tapsioss/theme run check`; `prebuild` runs it too, so
 * a broken set cannot be published.
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";
import { getFileMeta } from "../../../scripts/utils.ts";

const { dirname } = getFileMeta(import.meta.url);

const packageDir = path.resolve(dirname, "..");
const srcDir = path.join(packageDir, "src");
const jsonDir = path.join(packageDir, "figma-output-jsons");

/** Top-level groups of the primitive collection. */
const PRIMITIVE_ROOTS = ["Palette", "Font", "Number"];

/** Theme sets, keyed by the `<product>/<theme>` path they are emitted to. */
const THEMES: Record<string, string> = {
  "ride/light": "ride-theme-tokens/ride-light.json",
  "ride/dark": "ride-theme-tokens/ride-dark.json",
  "drive/light": "drive-theme-tokens/drive-light.json",
  "drive/dark": "drive-theme-tokens/drive-dark.json",
};

/** Generic fallback appended to each font family, keyed by the Figma name. */
const FAMILY_FALLBACK: Record<string, string> = {
  Base: "sans-serif",
  Mono: "monospace",
};

/* -------------------------------------------------------------------------- */
/* Naming — must match §"Naming" in AGENTS.md                                 */
/* -------------------------------------------------------------------------- */

const SEGMENT =
  /[0-9]+[a-z]+|[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z][a-z0-9]*|[0-9]+/g;

const segments = (...parts: string[]): string[] =>
  parts
    .flatMap(part => part.split(/[-_/\s]+/))
    .filter(Boolean)
    .flatMap(part => part.match(SEGMENT) ?? [])
    .map(segment => segment.toLowerCase());

const cssName = (...parts: string[]): string =>
  `--tapsi-${segments(...parts).join("-")}`;

const camel = (part: string): string => {
  const [head, ...rest] = segments(part);

  return (
    (head ?? "") + rest.map(s => s[0]!.toUpperCase() + s.slice(1)).join("")
  );
};

/* -------------------------------------------------------------------------- */
/* Values — must match §"Value rules" in AGENTS.md                            */
/* -------------------------------------------------------------------------- */

const rem = (value: number): string => {
  if (value === 0) return "0";

  return `${String(Number((value / 16).toFixed(6)))}rem`;
};

const cssColor = (raw: string): string => {
  const hex = raw.replace(/^#/, "").toLowerCase();

  if (hex.length === 6) return `#${hex}`;

  const channel = (at: number) => parseInt(hex.slice(at, at + 2), 16);
  const alpha = Number((channel(6) / 255).toFixed(2));

  return `rgba(${String(channel(0))}, ${String(channel(2))}, ${String(channel(4))}, ${String(alpha)})`;
};

/* -------------------------------------------------------------------------- */

type Leaf = { path: string[]; value: unknown };
type Json = Record<string, unknown>;

const walk = (node: Json, trail: string[] = []): Leaf[] =>
  Object.entries(node).flatMap(([key, value]) =>
    value !== null && typeof value === "object"
      ? walk(value as Json, [...trail, key])
      : [{ path: [...trail, key], value }],
  );

const dig = (node: Json, parts: string[]): unknown =>
  parts.reduce<unknown>(
    (acc, part) =>
      acc !== null && typeof acc === "object" ? (acc as Json)[part] : undefined,
    node,
  );

/**
 * Read a leaf out of a TS token set as a string.
 *
 * `null` means "not a leaf" — either absent, or a group where a value was
 * expected. Both are failures, and distinguishing them from a legitimate value
 * matters: stringifying a group would yield "[object Object]", which compares
 * unequal to everything and so would be reported as a value mismatch rather
 * than as the structural error it is.
 */
const leafOf = (node: Json, parts: string[]): string | null => {
  const value = dig(node, parts);

  if (typeof value === "string") return value;
  if (typeof value === "number" || typeof value === "boolean") {
    return String(value);
  }

  return null;
};

const DECL = /^\s*(--tapsi-[a-z0-9-]+)\s*:\s*([^;]+);/gm;
const REF = /^var\(\s*(--tapsi-[a-z0-9-]+)\s*\)$/;

/** Comment blocks, stripped before selectors are read. */
const COMMENTS = /\/\*[\s\S]*?\*\//g;

/** The text preceding each `{` — i.e. every selector that opens a rule block. */
const SELECTORS = /([^{}]+)\{/g;

/**
 * The selectors a file is required to declare its tokens under.
 *
 * This is checked because the rest of this script is selector-blind — it reads
 * declarations by regex and would happily pass a theme that had lost its scoped
 * selector. That failure is invisible: the tokens still resolve globally, so
 * everything looks right until someone tries to render two themes at once and
 * finds the switch does nothing.
 */
const expectedSelectors = (set: string): string[] => {
  if (set === "tokens") return [":root"];

  // `ride/light` -> `ride-light`. One attribute, not two: a theme is a
  // product/mode pair, and the token files are per pair, so the consumer-facing
  // value is the pair too.
  return [":root", `[data-tapsi-theme="${set.replace("/", "-")}"]`];
};

const parseCss = async (file: string) => {
  const css = await fs.readFile(file, "utf8");
  const out = new Map<string, string>();

  // Prettier wraps declarations past the print width, so a value can span
  // lines. Normalise whitespace: formatting is prettier's business, not ours.
  const normalise = (value: string) =>
    value
      .replace(/\s+/g, " ")
      .replace(/\(\s+/g, "(")
      .replace(/\s+\)/g, ")")
      .trim();

  for (const match of css.matchAll(DECL)) {
    out.set(match[1]!, normalise(match[2]!));
  }

  return out;
};

/** Assert a stylesheet opens exactly the rule blocks it is supposed to. */
const checkSelectors = async (file: string, set: string) => {
  const css = (await fs.readFile(file, "utf8")).replace(COMMENTS, "");
  const found = [...css.matchAll(SELECTORS)].map(m =>
    m[1]!
      .split(",")
      .map(s => s.trim())
      .filter(Boolean)
      .join(", "),
  );

  const want = expectedSelectors(set).join(", ");

  if (found.length !== 1 || found[0] !== want) {
    fail(
      `${set}.css declares its tokens under ${
        found.length === 0
          ? "no selector"
          : found.map(f => `\`${f}\``).join(" and ")
      }; expected exactly \`${want}\``,
    );
  }
};

const problems: string[] = [];
const fail = (message: string) => problems.push(message);

/** Follow a `var()` chain to the literal it bottoms out at. */
const resolve = (
  name: string,
  vars: Map<string, string>,
  seen = new Set<string>(),
): string | null => {
  if (seen.has(name)) return null;

  seen.add(name);

  const value = vars.get(name);

  if (value === undefined) return null;

  const ref = REF.exec(value);

  return ref ? resolve(ref[1]!, vars, seen) : value;
};

void (async () => {
  const readJson = async (rel: string) =>
    JSON.parse(await fs.readFile(path.join(jsonDir, rel), "utf8")) as Json;

  /* ---------------------------------------------------------- primitives */

  const primitiveJson = await readJson("primitive.json");
  const primitiveCss = await parseCss(path.join(srcDir, "tokens.css"));

  await checkSelectors(path.join(srcDir, "tokens.css"), "tokens");
  const primitiveTs = (await import(path.join(srcDir, "tokens.ts"))) as {
    tokens: Json;
  };

  /** The literal each primitive should carry, per the documented transforms. */
  const primitiveValue = ({ path: p, value }: Leaf): string => {
    if (p[0] === "Palette") return cssColor(value as string);
    if (p[0] === "Number") return rem(value as number);

    if (p[1] === "Family") {
      return `"${String(value)}", ${FAMILY_FALLBACK[p[2]!] ?? "sans-serif"}`;
    }

    // The Figma *key* is the real weight; the value is a label ("Regular").
    if (p[1] === "Weight") return p[2]!;
    if (p[1] === "Size") return rem(value as number);

    throw new Error(`no value rule for ${p.join("/")}`);
  };

  const expectedPrimitives = new Set<string>();

  for (const leaf of walk(primitiveJson)) {
    const name = cssName(...leaf.path);

    expectedPrimitives.add(name);

    const expected = primitiveValue(leaf);
    const actual = primitiveCss.get(name);

    if (actual === undefined) {
      fail(`tokens.css is missing ${name} (${leaf.path.join("/")})`);
    } else if (actual !== expected) {
      fail(`tokens.css: ${name} is "${actual}", expected "${expected}"`);
    }

    const tsPath = leaf.path.map(camel).join(".");
    const tsValue = leafOf(primitiveTs.tokens, leaf.path.map(camel));

    if (tsValue === null) {
      fail(`tokens.ts has no value at ${tsPath}`);
    } else if (tsValue !== expected) {
      fail(`tokens.ts: ${tsPath} is "${tsValue}", expected "${expected}"`);
    }
  }

  for (const name of primitiveCss.keys()) {
    if (!expectedPrimitives.has(name)) {
      fail(`tokens.css declares ${name}, which no export defines`);
    }
  }

  /* --------------------------------------------------------------- themes */

  let assertions = primitiveCss.size;

  for (const [set, rel] of Object.entries(THEMES)) {
    const json = await readJson(rel);
    const css = await parseCss(path.join(srcDir, `${set}.css`));

    await checkSelectors(path.join(srcDir, `${set}.css`), set);
    const ts = (await import(path.join(srcDir, `${set}.ts`))) as {
      tokens: Json;
    };

    const composition = new Map([...primitiveCss, ...css]);
    const expected = new Set<string>();

    for (const name of css.keys()) {
      if (primitiveCss.has(name)) {
        fail(`${set}.css: ${name} is already defined in tokens.css`);
      }
    }

    for (const { path: p, value } of walk(json)) {
      const name = cssName(...p);

      expected.add(name);

      const actual = css.get(name);

      if (actual === undefined) {
        fail(`${set}.css is missing ${name} (${p.join("/")})`);
        continue;
      }

      if (typeof value === "string") {
        // A reference. It must point at a real token, and be emitted as a
        // one-hop `var()` at exactly that name.
        const target = value.split(".");
        const collection = PRIMITIVE_ROOTS.includes(target[0]!)
          ? primitiveJson
          : json;

        if (dig(collection, target) === undefined) {
          fail(
            `${set}: ${p.join("/")} references ${value}, which does not exist`,
          );
          continue;
        }

        const want = `var(${cssName(...target)})`;

        if (actual !== want) {
          fail(`${set}.css: ${name} is "${actual}", expected "${want}"`);
        }
      } else if (REF.test(actual)) {
        fail(
          `${set}.css: ${name} is a reference, but the export gives a literal`,
        );
      } else {
        // A literal in the theme layer — sanctioned only for line heights.
        if (p[1] !== "Line-Height") {
          fail(
            `${set}.css: ${name} holds the literal "${actual}"; theme tokens ` +
              `must reference a primitive so the layer stays swappable`,
          );
        }

        const want = rem(value as number);

        if (actual !== want) {
          fail(`${set}.css: ${name} is "${actual}", expected "${want}"`);
        }
      }

      // TS must exist at the camelCase path and agree with the resolved chain.
      const tsPath = p.map(camel).join(".");
      const tsValue = leafOf(ts.tokens, p.map(camel));
      const resolved = resolve(name, composition);

      if (tsValue === null) {
        fail(`${set}.ts has no value at ${tsPath}`);
      } else if (resolved === null) {
        fail(`${set}.css: ${name} does not resolve to a literal`);
      } else if (tsValue !== resolved) {
        fail(
          `${set}: ${tsPath} is "${tsValue}" in TS but resolves to ` +
            `"${resolved}" in CSS`,
        );
      }

      assertions += 1;
    }

    for (const name of css.keys()) {
      if (!expected.has(name)) {
        fail(`${set}.css declares ${name}, which the export does not define`);
      }
    }
  }

  if (problems.length > 0) {
    for (const problem of problems) console.error(`❌ ${problem}`);

    console.error(`\n${String(problems.length)} problem(s).`);
    process.exit(1);
  }

  console.log(
    `✅ ${String(primitiveCss.size)} primitives + ${String(Object.keys(THEMES).length)} theme(s), ` +
      `${String(assertions)} tokens verified against figma-output-jsons/ — names, ` +
      `values, layering, and CSS/TS agreement.`,
  );
})();
